# Generated by Django 4.2 on 2023-09-27 18:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название продукта",
                        max_length=100,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Владелец продукта",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название урока",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        help_text="Ссылка на видео урока",
                        unique=True,
                        verbose_name="Ссылка на видео",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        help_text="Длительность просмотра урока (в секундах)",
                        verbose_name="Длительность",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        help_text="Продукты, в которых содержится урок",
                        related_name="lessons",
                        to="education.product",
                        verbose_name="Продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.CreateModel(
            name="ViewLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_time",
                    models.DurationField(
                        default=datetime.timedelta,
                        help_text="Общее время просмотра урока",
                        verbose_name="Время просмотра",
                    ),
                ),
                (
                    "last_view",
                    models.DateField(
                        auto_now=True,
                        help_text="Дата последнего просмотра урока",
                        verbose_name="Дата последнего просмотра",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Урок, просмотренный пользователем",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, просмотревший урок",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Просмотр урока",
                "verbose_name_plural": "Просмотры уроков",
                "unique_together": {("user", "lesson")},
            },
        ),
        migrations.CreateModel(
            name="ProductAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Продукт, к которому есть доступ",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="education.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь с доступом к продукту",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ к продукту",
                "verbose_name_plural": "Доступы к продуктам",
                "unique_together": {("user", "product")},
            },
        ),
    ]
