# Generated by Django 4.2 on 2023-09-27 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("education", "0002_lessonview_last_view_alter_productaccess_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LessonView",
            new_name="ViewLesson",
        ),
        migrations.AlterField(
            model_name="productaccess",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="education.product",
            ),
        ),
        migrations.AlterField(
            model_name="productaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
