# Generated by Django 4.2 on 2023-09-27 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("education", "0003_rename_lessonview_viewlesson_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="products",
            new_name="product",
        ),
        migrations.AlterUniqueTogether(
            name="productaccess",
            unique_together={("user", "product")},
        ),
    ]
