# Generated by Django 4.2 on 2023-09-27 14:20

import datetime

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("education", "0004_rename_products_lesson_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="viewlesson",
            name="viewed_time",
            field=models.DurationField(verbose_name=datetime.timedelta),
        ),
        migrations.AlterUniqueTogether(
            name="viewlesson",
            unique_together={("user", "lesson")},
        ),
    ]
