# Generated by Django 4.2 on 2023-09-25 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonview",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="lessonview",
            name="user",
        ),
        migrations.RemoveField(
            model_name="product",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="productaccess",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productaccess",
            name="user",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
        migrations.DeleteModel(
            name="LessonView",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductAccess",
        ),
    ]
